# Generated by Django 4.2.3 on 2023-07-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
