# Generated by Django 4.2.3 on 2023-07-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
